// @ts-nocheck
// This file is automatically generated. Do not edit.

export const firebaseConfig = {"apiKey":"AIzaSyDt-knN7O7FwcPvMtr5lwA4jEKFHSdSwGg","appId":"1:683983817672:web:41088417b67608e87c4efd","authDomain":"studio-8579609942-ed0a5.firebaseapp.com","measurementId":"","messagingSenderId":"683983817672","projectId":"studio-8579609942-ed0a5"};